name: agg
description: A dart port of Anti-Grain Geometry (AGG) C++ 2D graphic library
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:  
  image: ^4.5.4
  typed_data: any
  vector_math: ^2.2.0
  xml: ^6.5.0
  csslib: ^1.0.0
  archive: ^4.0.7
  #brotli: ^0.6.0
  ffi: ^2.1.3

dev_dependencies:
  test: any
  ffigen: ^19.0.0
  
  # glfw: ^0.2.4
  # pedantic: ^1.0.0
  # ffi_utils: ^0.1.1
  # ffi: ^0.1.3
  # opengl: ^0.3.4